---
- name: Create a hosted control plane cluster from a ClusterOrder
  hosts: localhost
  gather_facts: false

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  pre_tasks:
    - name: Set cluster order name
      ansible.builtin.set_fact:
        cluster_order_name: "{{ cluster_order.metadata.name }}"

    - name: Set lock holder identity
      ansible.builtin.set_fact:
        cluster_order_holder_id: >-
          {{ cluster_order_name }}-{{ awx_job_id | default("unknown") }}-{{
            lookup('community.general.random_string', special=false, numbers=false, upper=false)
          }}

    - name: Cluster order before defaults
      ansible.builtin.debug:
        var: cluster_order

    - name: Apply default settings
      ansible.builtin.include_role:
        name: cloudkit.service.cluster_settings

    - name: Cluster order after defaults
      ansible.builtin.debug:
        var: cluster_order

    - name: Extract template info
      ansible.builtin.include_role:
        name: cloudkit.service.extract_template_info

    - name: Determine working namespace
      ansible.builtin.include_role:
        name: cloudkit.service.cluster_working_namespace
      vars:
        cluster_working_namespace_cluster_order_name: "{{ cluster_order_name }}"

  tasks:
    - name: Acquire cluster lock
      ansible.builtin.include_role:
        name: cloudkit.service.lease
      vars:
        lease_state: present
        lease_holder: "{{ cluster_order_holder_id }}"
        lease_name: "cluster-{{ cluster_order_name }}-lock"

    - name: Add infrastructure finalizer to clusterorder
      ansible.builtin.include_role:
        name: cloudkit.service.finalizer
      vars:
        finalizer_state: present
        finalizer_name: "{{ cluster_order_infrastructure_finalizer }}"
        finalizer_target:
          api_version: cloudkit.openshift.io/v1alpha1
          kind: ClusterOrder
          namespace: "{{ lookup('env', 'POD_NAMESPACE') }}"
          name: "{{ cluster_order.metadata.name }}"

    - name: Display cluster order information
      ansible.builtin.debug:
        msg:
          - "Cluster order: {{ cluster_order.metadata.name }}"
          - "Cluster working namespace: {{ cluster_working_namespace }}"
          - "Template ID: {{ template_id }}"

    - name: Call the selected template
      ansible.builtin.include_role:
        name: "{{ template_id }}"
        tasks_from: "install"
